### PR TITLE
Different fixes

### PR DESCRIPTION
**Pull request by LarsMichelsen**
Please have a look at my notes in "Fix initial mode loading".

```
    // Adapt the leds to the current mode. Please note the differences between Mode and currentMode.
    //
    // Mode:        Is set by the config or the web interface to tell the lamp that a specific mode should
    //              be shown. The lamp will then change to that mode slowly (see adjustBrightnessAndSwitchMode())
    // currentMode: In case this is set to a mode name, the lamp came to the point where a mode should be
    //              asked to render it's pattern.
    //              During startup this is set to "". In this situation the mode should not be rendered, but
    //              adjustBrightnessAndSwitchMode() should be called to introduce Mode.
```

Did I get that right?

### CODE REVIEW

**Comment by thebigpotatoe** [comment]
All the commits in this pull are very useful, but https://github.com/thebigpotatoe/Super-Simple-RGB-WiFi-Lamp/pull/31/commits/8da9815a007d0c8cb85f495fb2f18837fb5ec220 is being tackled on multiple fronts. 

I'm still learning git, but is there a way to stash https://github.com/thebigpotatoe/Super-Simple-RGB-WiFi-Lamp/pull/31/commits/8da9815a007d0c8cb85f495fb2f18837fb5ec220 and come back to it later, or rebase it to a fresh pull request?

**Comment by LarsMichelsen** [comment]
Sure, no problem with git. I removed 8da9815 from this PR.

**Comment by LarsMichelsen** [comment]
Moved 8da9815 to dedicated PR #37

**Comment by thebigpotatoe** [comment]
Awesome, I really have to learn how to do that properly haha.

**Comment by thebigpotatoe** [comment]
Had a play, all seems to be good. Merging in.

**Pull request merged**
