### PR TITLE
Added 3 new modes.

### PR DESCRIPTION
**Pull request by Phantisy**
Added Sparkle, Color Wipe and Confetti. Also added global brightness from StefaanVanDooren's fork.

### CODE REVIEW

**Comment by Phantisy** [comment]
I could not figure out how to get my files to update in my original fork, so I just deleted my fork and re-forked and updated with my changes.

**Comment by thebigpotatoe** [comment]
Awesome, nice job. This is probably what I would have done also.

The three modes look great. Really well done on implementing the code, I'm really looking forward to testing these out when I get a chance.

One issue though is the global brightness. I have touched on why this repo cannot currently support such a thing in my discussions with Stephan on his pull requests [over here](https://github.com/thebigpotatoe/Super-Simple-RGB-WiFi-Lamp/pull/9#issuecomment-546797722). 

Summed up, global brightness wont be supported until I figure a way to allow existing and old modes to ignore a global brightness if they require it. And probably in the long run redesign and standardize how new modes should be written such that they can support a global brightness.

So for now, I'll pull in your new modes and have a play around with them to make sure they work. But also revert the global brightness commit for a revisit down the road. If you would like to have a global brightness in your code, I encourage you to keep it in your fork, and hopefully soonish I will be able to look into it.

**Comment by thebigpotatoe** [comment]
So there are a couple of options for merging by the seems of it. I want to keep the commit history clean and give you all the credit in this pull, so if you could either use `git revert` (preferred) or `git reset` on the brightness commit that would be fantastic. Otherwise it seems I can edit this pull request which will open a a pull of my own based on what you have done, but looks like I made the modes. Choice is yours.

I know it is not stated anywhere, but if you want to make pull requests in the future, I think it will be easier to manage if you do one pull per feature/addition, rather than adding multiple commits like in this pull.

**Comment by Phantisy** [comment]
Alright. I have kept the brightness for my person use, as it works well for me. I will revert brightness change and keep it out of this for the future.

**Comment by Phantisy** [comment]
I have reverted the Brightness change.

**Comment by thebigpotatoe** [comment]
Looks great. Really keen to give these modes a go. Thanks again.

**Pull request merged**
