### PR TITLE
New modes

### PR DESCRIPTION
**Pull request by jennytoo**
* New Fireflies mode. Similar in concept to Sparkle, but eases the LEDs in and out and runs several at a time on different timers with random timing.
* New Saturation Fade mode. Similar idea to Color Wipe or Rainbow, fills the strip up with a solid color, applying a sine wave to the saturation channel resulting in a pleasing gradient between the given color and white. Shifts the alignment along the strip over the span of 1..10 seconds, configurable.

### CODE REVIEW

**Comment by LarsMichelsen** [comment]
Cool effects. Both work for me :)

**Comment by jennytoo** [comment]
> Cool effects. Both work for me :)

Glad to hear that. I was a little worried I made errors during the cherry pick as I had to extract it from my main branch. :)

**Comment by thebigpotatoe** [comment]
Looks great. I'll have a play with them when I'm home after the Christmas period and merge them in.

**Comment by thebigpotatoe** [comment]
@jennytoo,

Lars has made some great changes to the New Modes with #36. We are refactoring how the modes will be sent to the website. If I get a chance to make these modes into the newer format I will, but for now I will hold off on merging these in until the new way of handling modes is complete.

**Comment by thebigpotatoe** [comment]
Ended up re basing the pull with the master and added 2 lines. Nice and easy.

Modes work great, awesome stuff!

**Comment by thebigpotatoe** [comment]
Cleaned up some stuff as well. Merging it in.

**Pull request merged**
